//! # panic-bomb (test fixture)
//!
//! Installs the nexum-sdk tracing facade (subscriber + panic hook) in
//! `init` and panics on every `on_event`. The hook writes the panic to
//! stderr and forwards it over the host logging call before the trap
//! reaches the supervisor, so one death leaves Stderr, HostInterface,
//! and Panic records on the run.
//!
//! Not a production module. Lives under `modules/fixtures/` so it is
//! obviously test-only.

#![cfg_attr(not(test), warn(unused_crate_dependencies))]
#![allow(clippy::too_many_arguments)]

wit_bindgen::generate!({
    path: "../../../wit/nexum-host",
    world: "nexum:host/event-module",
});

use nexum::host::{logging, types};

/// Routes facade lines to the bound host logging import.
///
/// Hand-rolled rather than generated by `bind_host_via_wit_bindgen!`:
/// this fixture binds only the minimal nexum world, so the generic
/// adapter would pull in unused chain/local-store impls and an unused
/// error converter (dead code under the `-D warnings` wasm build) for
/// the sole benefit of one log line. The sink below is the whole cost.
struct HostLogSink;

impl nexum_sdk::tracing::LogSink for HostLogSink {
    fn log(&self, level: nexum_sdk::Level, message: &str) {
        use nexum_sdk::Level;
        // `Level` is a set of associated consts, so compare rather than
        // match; the five tiers are total, hence the final `Trace` arm.
        let level = if level == Level::ERROR {
            logging::Level::Error
        } else if level == Level::WARN {
            logging::Level::Warn
        } else if level == Level::INFO {
            logging::Level::Info
        } else if level == Level::DEBUG {
            logging::Level::Debug
        } else {
            logging::Level::Trace
        };
        logging::log(level, message);
    }
}

struct PanicBomb;

impl Guest for PanicBomb {
    fn init(_config: Vec<(String, String)>) -> Result<(), HostError> {
        nexum_sdk::tracing::init(HostLogSink);
        tracing::info!("panic-bomb init (will panic)");
        Ok(())
    }

    fn on_event(_event: types::Event) -> Result<(), HostError> {
        panic!("panic-bomb detonated");
    }
}

export!(PanicBomb);
