//! # balance-tracker (example Shepherd module)
//!
//! On each block reads `eth_getBalance` for every `[config].addresses`
//! entry, persists the last value under `balance:{addr}`, and warns
//! when a balance moves more than `[config].change_threshold` wei.
//! Pure logic lives in `logic`; `lib.rs` is the
//! `#[nexum_sdk::module]` glue.

#![cfg_attr(not(test), warn(unused_crate_dependencies))]
#![allow(clippy::too_many_arguments)]

mod logic;

use std::sync::OnceLock;

use nexum::host::types;

static SETTINGS: OnceLock<logic::Settings> = OnceLock::new();

// `WitBindgenHost`, the fault `From` impls, and `install_tracing` (used
// by the handlers) are generated by the attribute alongside the
// wit-bindgen call and the `Guest`/`export!` glue.
struct BalanceTracker;

#[nexum_sdk::module]
impl BalanceTracker {
    fn init(config: Vec<(String, String)>) -> Result<(), Fault> {
        install_tracing();
        let cfg = logic::parse_config(&config)?;
        tracing::info!(
            "balance-tracker init: {} addresses, threshold={} wei",
            cfg.addresses.len(),
            cfg.change_threshold,
        );
        let _ = SETTINGS.set(cfg);
        Ok(())
    }

    fn on_block(block: types::Block) -> Result<(), Fault> {
        let Some(cfg) = SETTINGS.get() else {
            return Ok(());
        };
        logic::on_block(&WitBindgenHost, block.chain_id, cfg).map_err(Into::into)
    }
}
