//! # price-alert (example Shepherd module)
//!
//! Polls a Chainlink oracle on each block and warns when the price
//! crosses a `[config]`-supplied threshold on the configured side.
//! Demonstrates `chain::request` with an `alloy_sol_types` ABI decode
//! and the `nexum_sdk::chain` helpers. Pure logic lives in `strategy`;
//! `lib.rs` is the `#[nexum_sdk::module]` glue.

// wit_bindgen::generate! expands to host-import shims whose arity matches
// the WIT signatures, which can exceed clippy's too-many-arguments threshold.
#![cfg_attr(not(test), warn(unused_crate_dependencies))]
#![allow(clippy::too_many_arguments)]

mod strategy;

use std::sync::OnceLock;

use nexum::host::types;

static SETTINGS: OnceLock<strategy::Settings> = OnceLock::new();

// `WitBindgenHost`, the fault `From` impls, and `install_tracing` (used
// by the handlers) are generated by the attribute alongside the
// wit-bindgen call and the `Guest`/`export!` glue.
struct PriceAlert;

#[nexum_sdk::module]
impl PriceAlert {
    fn init(config: Vec<(String, String)>) -> Result<(), Fault> {
        install_tracing();
        let cfg = strategy::parse_config(&config)?;
        tracing::info!(
            "price-alert init: oracle={:#x} threshold={} direction={:?} every_n_blocks={}",
            cfg.oracle_address,
            cfg.threshold_scaled,
            cfg.direction,
            cfg.every_n_blocks,
        );
        let _ = SETTINGS.set(cfg);
        Ok(())
    }

    fn on_block(block: types::Block) -> Result<(), Fault> {
        let Some(cfg) = SETTINGS.get() else {
            return Ok(());
        };
        strategy::on_block(&WitBindgenHost, block.chain_id, cfg, block.number).map_err(Into::into)
    }
}
