//! # balance-tracker (example Shepherd module)
//!
//! Subscribes to blocks, reads `eth_getBalance(addr)` for every
//! address in `[config].addresses` (comma-separated), persists the
//! last seen value under `balance:{addr}` in local-store, and emits
//! a Warn-level log line when the balance changes by more than
//! `[config].change_threshold` wei since the previous block.
//!
//! ## Module layout
//!
//! - `strategy.rs` holds the pure logic and tests against
//!   `nexum_sdk::host::Host`. It does not know `wit-bindgen`
//!   exists.
//! - `lib.rs` (this file) declares the handlers and defers the
//!   per-cdylib glue to `#[nexum_sdk::module]`.
//!
//! ## Config
//!
//! ```toml
//! [config]
//! # Comma-separated list of 0x-prefixed 20-byte addresses.
//! addresses = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8,0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
//! # Change threshold in wei; an alert fires when the delta exceeds it.
//! change_threshold = "100000000000000000"  # 0.1 ETH
//! ```

#![cfg_attr(not(test), warn(unused_crate_dependencies))]
#![allow(clippy::too_many_arguments)]

mod strategy;

use std::sync::OnceLock;

use nexum::host::types;

static SETTINGS: OnceLock<strategy::Settings> = OnceLock::new();

// `WitBindgenHost`, the fault `From` impls, and `install_tracing` (used
// by the handlers) are generated by the attribute alongside the
// wit-bindgen call and the `Guest`/`export!` glue.
struct BalanceTracker;

#[nexum_sdk::module]
impl BalanceTracker {
    fn init(config: Vec<(String, String)>) -> Result<(), Fault> {
        install_tracing();
        let cfg = strategy::parse_config(&config)?;
        tracing::info!(
            "balance-tracker init: {} addresses, threshold={} wei",
            cfg.addresses.len(),
            cfg.change_threshold,
        );
        let _ = SETTINGS.set(cfg);
        Ok(())
    }

    fn on_block(block: types::Block) -> Result<(), Fault> {
        let Some(cfg) = SETTINGS.get() else {
            return Ok(());
        };
        strategy::on_block(&WitBindgenHost, block.chain_id, cfg).map_err(Into::into)
    }
}
