//! WIT bindings generated by `wasmtime::component::bindgen!`.
//!
//! The core host binds the `nexum:host/event-module` world: the six core
//! primitives. Outbound HTTP is not a `nexum:host` interface: it is
//! wasi:http, linked separately; clocks are ambient wasi:clocks. Domain
//! extensions such as cow-api bind their own world and wire themselves in
//! at the composition root; they are not part of this core surface.
//!
//! Every `Host` trait impl in `crate::host::impls` consumes types
//! generated here.

wasmtime::component::bindgen!({
    path: ["../../wit/nexum-host"],
    world: "nexum:host/event-module",
    imports: { default: async },
    exports: { default: async },
});
