//! WIT bindings generated by `wasmtime::component::bindgen!`.
//!
//! The core host binds the `nexum:host/event-module` world: the six core
//! primitives. Outbound HTTP is not a `nexum:host` interface: it is
//! wasi:http, linked separately; clocks are ambient wasi:clocks. Domain
//! extensions such as cow-api bind their own world and wire themselves in
//! at the composition root; they are not part of this core surface.
//!
//! Every `Host` trait impl in `crate::host::impls` consumes types
//! generated here.

wasmtime::component::bindgen!({
    path: ["../../wit/nexum-host"],
    world: "nexum:host/event-module",
    imports: { default: async },
    exports: { default: async },
});

/// WIT bindings for the second component kind: the `nexum:adapter/
/// venue-adapter` world. An adapter imports only the scoped transport it
/// needs (chain and messaging; outbound HTTP is wasi:http, linked and
/// allowlisted separately as for event-module) and exports the
/// `nexum:intent/adapter` face plus `init`. The shared `nexum:host`
/// interfaces are reused from the `event-module` bindings above via
/// `with`, so the `chain`/`messaging` `Host` impls and the `fault` type an
/// adapter sees are the very ones the core host constructs; the intent and
/// value-flow types generate here, their first non-test binding.
mod venue_adapter {
    wasmtime::component::bindgen!({
        path: [
            "../../wit/nexum-host",
            "../../wit/nexum-value-flow",
            "../../wit/nexum-intent",
            "../../wit/nexum-adapter",
        ],
        world: "nexum:adapter/venue-adapter",
        imports: { default: async },
        exports: { default: async },
        with: {
            "nexum:host/types": super::nexum::host::types,
            "nexum:host/chain": super::nexum::host::chain,
            "nexum:host/messaging": super::nexum::host::messaging,
        },
    });
}

pub use venue_adapter::VenueAdapter;

/// Bindgen smoke for the `nexum:value-flow` types package. The package has
/// no host consumer yet (the intent router that will bind it lands later),
/// so this compiles it under test only, through a throwaway world that
/// imports the interface. Its value is the identifier-hygiene gate: the
/// test names every generated type, variant, and field by its plain Rust
/// spelling, so a WIT id that collided with a Rust keyword would surface as
/// an `r#` escape and fail to compile here rather than in a downstream
/// binding.
#[cfg(test)]
mod value_flow_smoke {
    wasmtime::component::bindgen!({
        inline: "
            package nexum:value-flow-smoke;
            world smoke {
                import nexum:value-flow/types@0.1.0;
            }
        ",
        path: ["../../wit/nexum-value-flow"],
    });

    #[test]
    fn identifiers_bind_unescaped() {
        use nexum::value_flow::types::{Asset, AssetAmount, OffchainDesc, ServiceDesc, Settlement};

        let _ = Settlement::EvmChain(1);
        let _ = Settlement::Offchain(String::new());

        let service = ServiceDesc {
            kind: String::new(),
            summary: String::new(),
        };
        let offchain = OffchainDesc {
            domain: String::new(),
            summary: String::new(),
        };

        let _ = Asset::NativeToken(Settlement::EvmChain(1));
        let _ = Asset::Erc20((1, Vec::new()));
        let _ = Asset::Erc721((1, Vec::new(), Vec::new()));
        let _ = Asset::Erc1155((1, Vec::new(), Vec::new()));
        let _ = Asset::Service(service);
        let asset = Asset::Offchain(offchain);

        let amount = AssetAmount {
            asset,
            amount: Vec::new(),
        };
        assert!(amount.amount.is_empty());
    }
}

/// Bindgen smoke for the `nexum:intent` package, mirroring the value-flow
/// smoke above: no host consumer exists yet (the pool router lands later),
/// so the package compiles under test only, through a throwaway world that
/// imports the pool interface and, transitively, the types interface and
/// its value-flow dependency. The test names every generated type, case,
/// and field by its plain Rust spelling, and a dummy `pool` host impl pins
/// the three function signatures, so a keyword collision or an accidental
/// signature change fails this build rather than a downstream binding.
#[cfg(test)]
mod intent_smoke {
    wasmtime::component::bindgen!({
        inline: "
            package nexum:intent-smoke;
            world smoke {
                import nexum:intent/pool@0.1.0;
            }
        ",
        path: ["../../wit/nexum-value-flow", "../../wit/nexum-intent"],
    });

    use nexum::intent::types::{
        AuthScheme, FailReason, IntentHeader, IntentStatus, SubmitOutcome, UnsignedTx, VenueError,
    };
    use nexum::value_flow::types::Settlement;

    struct DummyPool;

    impl nexum::intent::pool::Host for DummyPool {
        fn submit(&mut self, _venue: String, _body: Vec<u8>) -> Result<SubmitOutcome, VenueError> {
            Err(VenueError::UnknownVenue)
        }

        fn status(
            &mut self,
            _venue: String,
            _receipt: Vec<u8>,
        ) -> Result<IntentStatus, VenueError> {
            Err(VenueError::UnknownVenue)
        }

        fn cancel(&mut self, _venue: String, _receipt: Vec<u8>) -> Result<(), VenueError> {
            Err(VenueError::UnknownVenue)
        }
    }

    #[test]
    fn identifiers_bind_unescaped() {
        use nexum::intent::pool::Host;

        let _ = AuthScheme::Eip712;
        let _ = AuthScheme::Eip1271;
        let _ = AuthScheme::Presign;
        let _ = AuthScheme::OffchainSig;
        let _ = AuthScheme::Unsigned;

        let header = IntentHeader {
            gives: Vec::new(),
            wants: Vec::new(),
            valid_until: None,
            settlement: Settlement::EvmChain(1),
            authorisation: AuthScheme::Eip712,
        };
        assert!(header.gives.is_empty() && header.wants.is_empty());

        let _ = IntentStatus::Pending;
        let _ = IntentStatus::Open;
        let _ = IntentStatus::Settled(None);
        let _ = IntentStatus::Failed(FailReason {
            code: String::new(),
            detail: String::new(),
        });
        let _ = IntentStatus::Expired;
        let _ = IntentStatus::Cancelled;

        let tx = UnsignedTx {
            chain_id: 1,
            to: Vec::new(),
            value: Vec::new(),
            input: Vec::new(),
        };
        let _ = SubmitOutcome::Accepted(Vec::new());
        let _ = SubmitOutcome::RequiresSigning(tx);

        let _ = VenueError::InvalidBody(String::new());
        let _ = VenueError::InvalidReceipt;
        let _ = VenueError::Rejected(String::new());
        let _ = VenueError::Denied(String::new());
        let _ = VenueError::Unsupported(String::new());
        let _ = VenueError::Unavailable(String::new());
        let _ = VenueError::InternalError(String::new());

        let mut pool = DummyPool;
        assert!(pool.submit(String::new(), Vec::new()).is_err());
        assert!(pool.status(String::new(), Vec::new()).is_err());
        assert!(pool.cancel(String::new(), Vec::new()).is_err());
    }
}
