//! Declarative macro that generates the `WitBindgenHost` adapter
//! every Shepherd module ships in `lib.rs`.
//!
//! Before this macro existed, each module hand-rolled ~80 lines of
//! mechanical glue: the `struct WitBindgenHost;` plus 4 trait impls
//! (`ChainHost`, `LocalStoreHost`, `CowApiHost`, `LoggingHost`) plus
//! `convert_err` / `sdk_err_into_wit` / `convert_level`. The code
//! differed across modules in zero places that were not bugs.
//!
//! The macro assumes the module compiles against
//! `shepherd:cow/shepherd` with `wit_bindgen::generate!({ ...,
//! generate_all })`, so the standard wit-bindgen output paths
//! (`nexum::host::chain`, `nexum::host::local_store`, etc., plus the
//! crate-root `HostError`) are in scope at the call site. Modules
//! using a different world need to keep their own adapter for now.
//!
//! Usage in a module's `lib.rs`:
//!
//! ```ignore
//! wit_bindgen::generate!({ /* ... */ });
//! shepherd_sdk::bind_host_via_wit_bindgen!();
//! // `WitBindgenHost`, `convert_err`, `sdk_err_into_wit`,
//! // `convert_level` are now in scope, with the wit-bindgen and SDK
//! // types tied together through identifier resolution.
//! ```

/// Generate `WitBindgenHost` + the four `*Host` trait impls + the
/// error / level converters. See module docs.
///
/// Macro hygiene note: `macro_rules!` is not hygienic for type names
/// or function items, so the names `WitBindgenHost`, `convert_err`,
/// `sdk_err_into_wit`, and `convert_level` are intentionally visible
/// in the caller's scope.
#[macro_export]
macro_rules! bind_host_via_wit_bindgen {
    () => {
        /// Wraps the module's per-cdylib wit-bindgen imports so the
        /// strategy can hold a `&impl Host` instead of dispatching on
        /// the free functions directly. Generated by
        /// `shepherd_sdk::bind_host_via_wit_bindgen!`.
        struct WitBindgenHost;

        impl $crate::host::ChainHost for WitBindgenHost {
            fn request(
                &self,
                chain_id: u64,
                method: &str,
                params: &str,
            ) -> ::core::result::Result<::std::string::String, $crate::host::HostError> {
                nexum::host::chain::request(chain_id, method, params).map_err(convert_err)
            }
        }

        impl $crate::host::LocalStoreHost for WitBindgenHost {
            fn get(
                &self,
                key: &str,
            ) -> ::core::result::Result<
                ::core::option::Option<::std::vec::Vec<u8>>,
                $crate::host::HostError,
            > {
                nexum::host::local_store::get(key).map_err(convert_err)
            }
            fn set(
                &self,
                key: &str,
                value: &[u8],
            ) -> ::core::result::Result<(), $crate::host::HostError> {
                nexum::host::local_store::set(key, value).map_err(convert_err)
            }
            fn delete(&self, key: &str) -> ::core::result::Result<(), $crate::host::HostError> {
                nexum::host::local_store::delete(key).map_err(convert_err)
            }
            fn list_keys(
                &self,
                prefix: &str,
            ) -> ::core::result::Result<
                ::std::vec::Vec<::std::string::String>,
                $crate::host::HostError,
            > {
                nexum::host::local_store::list_keys(prefix).map_err(convert_err)
            }
        }

        impl $crate::host::CowApiHost for WitBindgenHost {
            fn submit_order(
                &self,
                chain_id: u64,
                body: &[u8],
            ) -> ::core::result::Result<::std::string::String, $crate::host::HostError> {
                shepherd::cow::cow_api::submit_order(chain_id, body).map_err(convert_err)
            }

            fn cow_api_request(
                &self,
                chain_id: u64,
                method: &str,
                path: &str,
                body: ::core::option::Option<&str>,
            ) -> ::core::result::Result<::std::string::String, $crate::host::HostError> {
                shepherd::cow::cow_api::request(chain_id, method, path, body).map_err(convert_err)
            }
        }

        impl $crate::host::LoggingHost for WitBindgenHost {
            fn log(&self, level: $crate::host::LogLevel, message: &str) {
                nexum::host::logging::log(convert_level(level), message);
            }
        }

        /// Lift a wit-bindgen `HostError` (per-cdylib) into the SDK's
        /// host-neutral `HostError`. Exhaustive on `HostErrorKind`
        /// per the rust-idiomatic rule against wildcarded enum
        /// conversions.
        fn convert_err(e: HostError) -> $crate::host::HostError {
            $crate::host::HostError {
                domain: e.domain,
                kind: match e.kind {
                    nexum::host::types::HostErrorKind::Unsupported => {
                        $crate::host::HostErrorKind::Unsupported
                    }
                    nexum::host::types::HostErrorKind::Unavailable => {
                        $crate::host::HostErrorKind::Unavailable
                    }
                    nexum::host::types::HostErrorKind::Denied => {
                        $crate::host::HostErrorKind::Denied
                    }
                    nexum::host::types::HostErrorKind::RateLimited => {
                        $crate::host::HostErrorKind::RateLimited
                    }
                    nexum::host::types::HostErrorKind::Timeout => {
                        $crate::host::HostErrorKind::Timeout
                    }
                    nexum::host::types::HostErrorKind::InvalidInput => {
                        $crate::host::HostErrorKind::InvalidInput
                    }
                    nexum::host::types::HostErrorKind::Internal => {
                        $crate::host::HostErrorKind::Internal
                    }
                },
                code: e.code,
                message: e.message,
                data: e.data,
            }
        }

        /// Reverse direction: lift the SDK `HostError` back into the
        /// per-cdylib wit-bindgen `HostError` so `Guest::init` /
        /// `Guest::on_event` can return what wit-bindgen expects.
        ///
        /// Carries a wildcard arm because `$crate::host::HostErrorKind`
        /// is `#[non_exhaustive]`: a future SDK-side variant
        /// must compile in module crates without source changes. Falls
        /// back to `Internal` as the safest conservative remapping.
        fn sdk_err_into_wit(e: $crate::host::HostError) -> HostError {
            HostError {
                domain: e.domain,
                kind: match e.kind {
                    $crate::host::HostErrorKind::Unsupported => {
                        nexum::host::types::HostErrorKind::Unsupported
                    }
                    $crate::host::HostErrorKind::Unavailable => {
                        nexum::host::types::HostErrorKind::Unavailable
                    }
                    $crate::host::HostErrorKind::Denied => {
                        nexum::host::types::HostErrorKind::Denied
                    }
                    $crate::host::HostErrorKind::RateLimited => {
                        nexum::host::types::HostErrorKind::RateLimited
                    }
                    $crate::host::HostErrorKind::Timeout => {
                        nexum::host::types::HostErrorKind::Timeout
                    }
                    $crate::host::HostErrorKind::InvalidInput => {
                        nexum::host::types::HostErrorKind::InvalidInput
                    }
                    $crate::host::HostErrorKind::Internal => {
                        nexum::host::types::HostErrorKind::Internal
                    }
                    // `$crate::host::HostErrorKind` is `#[non_exhaustive]`.
                    // Fall back to `Internal`.
                    _ => nexum::host::types::HostErrorKind::Internal,
                },
                code: e.code,
                message: e.message,
                data: e.data,
            }
        }

        /// Translate the SDK `LogLevel` into the wit-bindgen
        /// `logging::Level`.
        ///
        /// Carries a wildcard arm because `$crate::host::LogLevel` is
        /// `#[non_exhaustive]`: a future SDK-side level
        /// must compile in module crates without source changes. Falls
        /// back to `Info` as the most neutral default.
        fn convert_level(l: $crate::host::LogLevel) -> nexum::host::logging::Level {
            match l {
                $crate::host::LogLevel::Trace => nexum::host::logging::Level::Trace,
                $crate::host::LogLevel::Debug => nexum::host::logging::Level::Debug,
                $crate::host::LogLevel::Info => nexum::host::logging::Level::Info,
                $crate::host::LogLevel::Warn => nexum::host::logging::Level::Warn,
                $crate::host::LogLevel::Error => nexum::host::logging::Level::Error,
                // `$crate::host::LogLevel` is `#[non_exhaustive]`.
                // Fall back to `Info`.
                _ => nexum::host::logging::Level::Info,
            }
        }
    };
}
