//! WIT bindings generated by `wasmtime::component::bindgen!`.
//!
//! Binds the `nexum:host/event-module` world (the six core primitives).
//! Outbound HTTP is wasi:http, linked separately; clocks are ambient
//! wasi:clocks. `nexum:host` is a leaf package: the host `event` variant
//! carries a status transition as opaque bytes. An extension remaps onto these
//! shared interfaces with `with`, so the `Host` impls and `fault` type its
//! components see are the ones the core host constructs. `PartialEq` is derived
//! so extension services can compare event payloads.

wasmtime::component::bindgen!({
    path: ["../../../wit/nexum-host"],
    world: "nexum:host/event-module",
    imports: { default: async },
    exports: { default: async },
    additional_derives: [PartialEq],
});
