//! WIT bindings generated by `wasmtime::component::bindgen!`.
//!
//! The core host binds the `nexum:host/event-module` world: the six core
//! primitives. Outbound HTTP is not a `nexum:host` interface: it is
//! wasi:http, linked separately; clocks are ambient wasi:clocks. Domain
//! extensions bind their own world and wire themselves in at the
//! composition root; they are not part of this core surface.
//!
//! Every `Host` trait impl in `crate::host::impls` consumes types
//! generated here.
//!
//! `nexum:host` is a leaf package: the host `event` variant carries a
//! status transition as opaque bytes, so the core world resolves against
//! `wit/nexum-host` alone; the group `wit/deps.toml` and its lock stay
//! empty. An extension's bindgen remaps onto the shared
//! interfaces here with `with`, so the `Host` impls and the `fault` type
//! its components see are the very ones the core host constructs.
//! `PartialEq` is derived so extension services can compare event payloads.

wasmtime::component::bindgen!({
    path: ["../../wit/nexum-host"],
    world: "nexum:host/event-module",
    imports: { default: async },
    exports: { default: async },
    additional_derives: [PartialEq],
});
