//! Declarative macro that generates the `WitBindgenHost` adapter
//! every module ships in `lib.rs`.
//!
//! Before this macro existed, each module hand-rolled ~80 lines of
//! mechanical glue: the `struct WitBindgenHost;` plus the core trait
//! impls (`ChainHost`, `LocalStoreHost`, `LoggingHost`) plus
//! `convert_chain_err` / `convert_fault` / `sdk_fault_into_wit` /
//! `convert_level`. The code differed across modules in zero places
//! that were not bugs.
//!
//! The macro assumes the module compiles against a world that
//! includes `nexum:host/event-module` with `wit_bindgen::generate!({
//! ..., generate_all })`, so the standard wit-bindgen output paths
//! (`nexum::host::chain`, `nexum::host::local_store`, etc., plus the
//! crate-root `Fault`) are in scope at the call site. Modules
//! using a different world need to keep their own adapter for now.
//!
//! A domain SDK layers its own interfaces on top by invoking this
//! macro and adding trait impls for the same `WitBindgenHost` (the
//! CoW SDK's `bind_cow_host_via_wit_bindgen!` does exactly that).
//!
//! Usage in a module's `lib.rs`:
//!
//! ```ignore
//! wit_bindgen::generate!({ /* ... */ });
//! nexum_sdk::bind_host_via_wit_bindgen!();
//! // `WitBindgenHost`, `convert_chain_err`, `convert_fault`,
//! // `sdk_fault_into_wit`, `convert_level`, `HostLogSink`, and
//! // `install_tracing` are now in
//! // scope, with the wit-bindgen and SDK types tied together through
//! // identifier resolution. Call `install_tracing()` once at the top
//! // of `Guest::init` to route `tracing::info!(...)` to the host. A
//! // `From<chain-log> for nexum_sdk::events::Log` is also emitted so
//! // `on_event` maps a chain-logs batch straight to `Vec<Log>`.
//! ```

/// Generate `WitBindgenHost` + the core `*Host` trait impls + the
/// error / level converters. See module docs.
///
/// Macro hygiene note: `macro_rules!` is not hygienic for type names
/// or function items, so the names `WitBindgenHost`, `convert_chain_err`,
/// `convert_fault`, `sdk_fault_into_wit`, `convert_level`, `HostLogSink`,
/// and `install_tracing` are intentionally visible in the caller's scope.
#[macro_export]
macro_rules! bind_host_via_wit_bindgen {
    () => {
        /// Wraps the module's per-cdylib wit-bindgen imports so the
        /// strategy can hold a `&impl Host` instead of dispatching on
        /// the free functions directly. Generated by
        /// `nexum_sdk::bind_host_via_wit_bindgen!`.
        struct WitBindgenHost;

        impl $crate::host::ChainHost for WitBindgenHost {
            fn request(
                &self,
                chain_id: u64,
                method: &str,
                params: &str,
            ) -> ::core::result::Result<::std::string::String, $crate::host::ChainError> {
                nexum::host::chain::request(chain_id, method, params).map_err(convert_chain_err)
            }
        }

        impl $crate::host::LocalStoreHost for WitBindgenHost {
            fn get(
                &self,
                key: &str,
            ) -> ::core::result::Result<
                ::core::option::Option<::std::vec::Vec<u8>>,
                $crate::host::Fault,
            > {
                nexum::host::local_store::get(key).map_err(convert_fault)
            }
            fn set(
                &self,
                key: &str,
                value: &[u8],
            ) -> ::core::result::Result<(), $crate::host::Fault> {
                nexum::host::local_store::set(key, value).map_err(convert_fault)
            }
            fn delete(&self, key: &str) -> ::core::result::Result<(), $crate::host::Fault> {
                nexum::host::local_store::delete(key).map_err(convert_fault)
            }
            fn list_keys(
                &self,
                prefix: &str,
            ) -> ::core::result::Result<::std::vec::Vec<::std::string::String>, $crate::host::Fault>
            {
                nexum::host::local_store::list_keys(prefix).map_err(convert_fault)
            }
        }

        impl $crate::host::LoggingHost for WitBindgenHost {
            fn log(&self, level: $crate::Level, message: &str) {
                nexum::host::logging::log(convert_level(level), message);
            }
        }

        /// Lift the wit-bindgen `chain.chain-error` (per-cdylib) into
        /// the SDK's host-neutral `ChainError`. Exhaustive on both the
        /// `Fault` vocabulary and the `RpcError` shape.
        fn convert_chain_err(e: nexum::host::chain::ChainError) -> $crate::host::ChainError {
            match e {
                nexum::host::chain::ChainError::Fault(f) => {
                    $crate::host::ChainError::Fault(convert_fault(f))
                }
                nexum::host::chain::ChainError::Rpc(r) => {
                    $crate::host::ChainError::Rpc($crate::host::RpcError {
                        code: r.code,
                        message: r.message,
                        data: r.data.map(::core::convert::Into::into),
                    })
                }
            }
        }

        /// Lift the wit-bindgen `types.fault` (per-cdylib) into the
        /// SDK's `Fault`. Exhaustive on the seven-case vocabulary; the
        /// `rate-limited` backoff record maps field for field.
        fn convert_fault(f: nexum::host::types::Fault) -> $crate::host::Fault {
            match f {
                nexum::host::types::Fault::Unsupported(s) => $crate::host::Fault::Unsupported(s),
                nexum::host::types::Fault::Unavailable(s) => $crate::host::Fault::Unavailable(s),
                nexum::host::types::Fault::Denied(s) => $crate::host::Fault::Denied(s),
                nexum::host::types::Fault::RateLimited(rl) => {
                    $crate::host::Fault::RateLimited($crate::host::RateLimit {
                        retry_after_ms: rl.retry_after_ms,
                    })
                }
                nexum::host::types::Fault::Timeout => $crate::host::Fault::Timeout,
                nexum::host::types::Fault::InvalidInput(s) => $crate::host::Fault::InvalidInput(s),
                nexum::host::types::Fault::Internal(s) => $crate::host::Fault::Internal(s),
            }
        }

        /// Reverse direction: lower the SDK [`Fault`](
        /// $crate::host::Fault) back into the per-cdylib wit-bindgen
        /// `Fault` so `Guest::init` / `Guest::on_event` can return what
        /// the export signature expects.
        ///
        /// Carries a wildcard arm because `$crate::host::Fault` is
        /// `#[non_exhaustive]`: a future SDK-side case must compile in
        /// module crates without source changes. Falls back to
        /// `internal` carrying the `Display` detail.
        fn sdk_fault_into_wit(f: $crate::host::Fault) -> nexum::host::types::Fault {
            use nexum::host::types::{Fault as WitFault, RateLimit as WitRateLimit};
            match f {
                $crate::host::Fault::Unsupported(s) => WitFault::Unsupported(s),
                $crate::host::Fault::Unavailable(s) => WitFault::Unavailable(s),
                $crate::host::Fault::Denied(s) => WitFault::Denied(s),
                $crate::host::Fault::RateLimited(rl) => WitFault::RateLimited(WitRateLimit {
                    retry_after_ms: rl.retry_after_ms,
                }),
                $crate::host::Fault::Timeout => WitFault::Timeout,
                $crate::host::Fault::InvalidInput(s) => WitFault::InvalidInput(s),
                $crate::host::Fault::Internal(s) => WitFault::Internal(s),
                // `$crate::host::Fault` is `#[non_exhaustive]`; a future
                // SDK case lands here as `internal`.
                other => WitFault::Internal(::std::string::ToString::to_string(&other)),
            }
        }

        /// Translate a `tracing_core::Level` into the wit-bindgen
        /// `logging::Level` wire enum. `Level` is a set of associated
        /// consts, not a matchable enum, so compare rather than match;
        /// the five tiers are total, so the final arm is `Trace`.
        fn convert_level(level: $crate::Level) -> nexum::host::logging::Level {
            use $crate::Level;
            if level == Level::ERROR {
                nexum::host::logging::Level::Error
            } else if level == Level::WARN {
                nexum::host::logging::Level::Warn
            } else if level == Level::INFO {
                nexum::host::logging::Level::Info
            } else if level == Level::DEBUG {
                nexum::host::logging::Level::Debug
            } else {
                nexum::host::logging::Level::Trace
            }
        }

        /// Rebuild the native alloy log from the per-cdylib wit-bindgen
        /// `chain-log` record. The one conversion home for the guest WIT
        /// edge: strategies receive `nexum_sdk::events::Log`, never the
        /// wire record. Assembly logic lives in `nexum_sdk::events`.
        impl ::core::convert::From<nexum::host::types::ChainLog> for $crate::events::Log {
            fn from(log: nexum::host::types::ChainLog) -> Self {
                $crate::events::ChainLogParts {
                    address: &log.address,
                    topics: &log.topics,
                    data: &log.data,
                    block_hash: log.block_hash.as_deref(),
                    block_number: log.block_number,
                    block_timestamp: log.block_timestamp,
                    transaction_hash: log.transaction_hash.as_deref(),
                    transaction_index: log.transaction_index,
                    log_index: log.log_index,
                    removed: log.removed,
                }
                .into()
            }
        }

        /// Routes guest `tracing` events to the bound host logging call.
        struct HostLogSink;

        impl $crate::tracing::LogSink for HostLogSink {
            fn log(&self, level: $crate::Level, message: &str) {
                <WitBindgenHost as $crate::host::LoggingHost>::log(&WitBindgenHost, level, message);
            }
        }

        /// Install the guest tracing facade and panic hook, forwarding
        /// through the bound host logging call. Call once at the top of
        /// `Guest::init` so `tracing::info!(...)` reaches the host.
        fn install_tracing() {
            $crate::tracing::init(HostLogSink);
        }
    };
}
