//! # http-probe (example Shepherd module)
//!
//! On each matching block fetches the allowlisted `[config].probe_url`
//! over wasi:http and logs its status, then fetches `[config].denied_url`
//! and asserts the `[capabilities.http].allow` gate denies it.
//! Demonstrates the SDK `http::Fetch` seam and the allowlist denial
//! path. Pure logic lives in `strategy`; `lib.rs` is the
//! `#[nexum_sdk::module]` glue.

// wit_bindgen::generate! expands to host-import shims whose arity matches
// the WIT signatures, which can exceed clippy's too-many-arguments threshold.
#![cfg_attr(not(test), warn(unused_crate_dependencies))]
#![allow(clippy::too_many_arguments)]

mod strategy;

use std::sync::OnceLock;

use nexum::host::types;

static SETTINGS: OnceLock<strategy::Settings> = OnceLock::new();

// The fault `From` impls and `install_tracing` (used by the handlers) are
// generated by the attribute alongside the wit-bindgen call and the
// `Guest`/`export!` glue.
struct HttpProbe;

#[nexum_sdk::module]
impl HttpProbe {
    fn init(config: Vec<(String, String)>) -> Result<(), Fault> {
        install_tracing();
        let cfg = strategy::parse_config(&config)?;
        tracing::info!(
            "http-probe init: probe_url={} denied_url={} every_n_blocks={}",
            cfg.probe_url,
            cfg.denied_url,
            cfg.every_n_blocks,
        );
        let _ = SETTINGS.set(cfg);
        Ok(())
    }

    fn on_block(block: types::Block) -> Result<(), Fault> {
        let Some(cfg) = SETTINGS.get() else {
            return Ok(());
        };
        strategy::on_block(&nexum_sdk::http::WasiFetch, cfg, block.number).map_err(Into::into)
    }
}
